### ISSUE TITLE
save credentials

### ISSUE THREAD

**Issue by theoneandonly-vector** [EmpireProject/EmpireMobile#2]
hey there, pls. integrate an option to save the login details like ip:port username and password.
thx :)

**Comment by P1CKLES** [comment]
Are you primarily using the Android or iOS version?

**Comment by theoneandonly-vector** [comment]
android

Am Mo., 7. Jan. 2019 um 21:27 Uhr schrieb Shannon Lucas <
notifications@github.com>:

> Are you primarily using the Android or iOS version?
>
> On Tue, Jan 1, 2019 at 8:13 AM theoneandonly-vector <

**Comment by P1CKLES** [comment]
cool, I'll work on adding that to the Android release first.

**Comment by P1CKLES** [comment]
Hey there, I finally got everything pushed up to github.  You can now save
creds in both the Android and iOS apps.
Sorry for the delay.

**Comment by theoneandonly-vector** [comment]
nice, thx :)
the release-apk still doesn't save the creds for me.

**Comment by P1CKLES** [comment]
> nice, thx :)
> the release-apk still doesn't save the creds for me.

Sorry, I forgot to build a new signed APK after updating the code.  I have rolled a new apk and pushed that up as well.  Let me know if you run into any other issues.  :)

**Comment by theoneandonly-vector** [comment]
thx :)
