### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by lusifer123** [EmpireProject/EmpireMobile#3]
When i run command  it's showing error please help me to fix this

`kali@kali:~/Desktop/Empire/setup$ sudo ./install.sh
--2021-05-04 07:59:19--  http://ftp.us.debian.org/debian/pool/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u7_amd64.deb
Resolving ftp.us.debian.org (ftp.us.debian.org)... 208.80.154.15, 64.50.236.52, 64.50.233.100, ...
Connecting to ftp.us.debian.org (ftp.us.debian.org)|208.80.154.15|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-05-04 07:59:19 ERROR 404: Not Found.

dpkg: error: cannot access archive 'libssl1.0.0_1.0.1t-1+deb8u7_amd64.deb': No such file or directory
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'python-dev-is-python2' instead of 'python-dev'
Package python-m2crypto is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package python-pip is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python3-pip

E: Package 'python-m2crypto' has no installation candidate
E: Package 'python-pip' has no installation candidate
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.                                                                      
Requirement already up-to-date: pip in /usr/local/lib/python2.7/dist-packages (20.3.4)
WARNING: You are using pip version 20.3.4; however, version 21.1 is available.
You should consider upgrading via the '/usr/bin/python2 -m pip install --upgrade pip' command.                    
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.                                                                      
Collecting urllib3<1.23,>=1.21.1
  Using cached urllib3-1.22-py2.py3-none-any.whl (132 kB)
Collecting requests==2.18.4
  Using cached requests-2.18.4-py2.py3-none-any.whl (88 kB)
Requirement already satisfied: setuptools in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3)) (44.1.1)
Collecting iptools
  Using cached iptools-0.7.0-py2.py3-none-any.whl (16 kB)
Collecting pydispatcher
  Using cached PyDispatcher-2.0.5.tar.gz (34 kB)
Collecting flask
  Using cached Flask-1.1.2-py2.py3-none-any.whl (94 kB)
Collecting macholib
  Using cached macholib-1.14-py2.py3-none-any.whl (37 kB)
Collecting dropbox
  Using cached dropbox-11.7.0-py2-none-any.whl (563 kB)
Collecting pyOpenSSL==17.2.0
  Using cached pyOpenSSL-17.2.0-py2.py3-none-any.whl (52 kB)
Collecting pyinstaller
  Using cached pyinstaller-4.1.tar.gz (3.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python2 /usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp1OI5sV                                                                                   
       cwd: /tmp/pip-install-O8HfcX/pyinstaller                                                                   
  Complete output (19 lines):                                                                                     
  Traceback (most recent call last):                                                                              
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>        
      main()                                                                                                      
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 263, in main            
      json_out['return_val'] = hook(**hook_input['kwargs'])                                                       
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel                                                                                                      
      return hook(config_settings)                                                                                
    File "/usr/local/lib/python2.7/dist-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel                                                                                                               
      return self._get_build_requires(config_settings, requirements=['wheel'])                                    
    File "/usr/local/lib/python2.7/dist-packages/setuptools/build_meta.py", line 127, in _get_build_requires      
      self.run_setup()                                                                                            
    File "/usr/local/lib/python2.7/dist-packages/setuptools/build_meta.py", line 243, in run_setup                
      self).run_setup(setup_script=setup_script)                                                                  
    File "/usr/local/lib/python2.7/dist-packages/setuptools/build_meta.py", line 142, in run_setup                
      exec(compile(code, __file__, 'exec'), locals())                                                             
    File "setup.py", line 63                                                                                      
      file=sys.stderr)                                                                                            
          ^                                                                                                       
  SyntaxError: invalid syntax                                                                                     
  ----------------------------------------                                                                        
ERROR: Command errored out with exit status 1: /usr/bin/python2 /usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp1OI5sV Check the logs for full command output.        
WARNING: You are using pip version 20.3.4; however, version 21.1 is available.
You should consider upgrading via the '/usr/bin/python2 -m pip install --upgrade pip' command.                    
cat: /etc/lsb-release: No such file or directory
cat: /etc/lsb-release: No such file or directory
cat: /etc/lsb-release: No such file or directory
cat: /etc/lsb-release: No such file or directory
ls: cannot access '/opt/microsoft/powershell/*/DELETE_ME_TO_DISABLE_CONSOLEHOST_TELEMETRY': No such file or directory
xar-1.5.2/
xar-1.5.2/lib/
xar-1.5.2/lib/fbsdattr.c
xar-1.5.2/lib/filetree.h
xar-1.5.2/lib/stat.c
xar-1.5.2/lib/hash.c
xar-1.5.2/lib/ext2.h
xar-1.5.2/lib/darwinattr.h
xar-1.5.2/lib/libxar.la.in.in
xar-1.5.2/lib/archive.c
xar-1.5.2/lib/subdoc.c
xar-1.5.2/lib/script.c
xar-1.5.2/lib/script.h
xar-1.5.2/lib/arcmod.c
xar-1.5.2/lib/arcmod.h
xar-1.5.2/lib/b64.c
xar-1.5.2/lib/subdoc.h
xar-1.5.2/lib/filetree.c
xar-1.5.2/lib/bzxar.c
xar-1.5.2/lib/ext2.c
xar-1.5.2/lib/fbsdattr.h
xar-1.5.2/lib/linuxattr.c
xar-1.5.2/lib/macho.c
xar-1.5.2/lib/ea.h
xar-1.5.2/lib/appledouble.h
xar-1.5.2/lib/darwinattr.c
xar-1.5.2/lib/util.h
xar-1.5.2/lib/util.c
xar-1.5.2/lib/hash.h
xar-1.5.2/lib/zxar.c
xar-1.5.2/lib/data.h
xar-1.5.2/lib/zxar.h
xar-1.5.2/lib/signature.h
xar-1.5.2/lib/bzxar.h
xar-1.5.2/lib/macho.h
xar-1.5.2/lib/signature.c
xar-1.5.2/lib/b64.h
xar-1.5.2/lib/err.c
xar-1.5.2/lib/asprintf.h
xar-1.5.2/lib/stat.h
xar-1.5.2/lib/io.h
xar-1.5.2/lib/linuxattr.h
xar-1.5.2/lib/io.c
xar-1.5.2/lib/ea.c
xar-1.5.2/lib/archive.h
xar-1.5.2/lib/data.c
xar-1.5.2/lib/Makefile.inc.in
xar-1.5.2/cfgoutputs.stamp.in
xar-1.5.2/cfghdrs.stamp.in
xar-1.5.2/config.guess
xar-1.5.2/INSTALL
xar-1.5.2/include/
xar-1.5.2/include/config.h.in
xar-1.5.2/include/xar.h.in
xar-1.5.2/configure
xar-1.5.2/test/
xar-1.5.2/test/checksums
xar-1.5.2/test/functions
xar-1.5.2/test/attr
xar-1.5.2/test/data.xsl
xar-1.5.2/test/buffer.c
xar-1.5.2/test/compression
xar-1.5.2/test/heap1.xsl
xar-1.5.2/test/data
xar-1.5.2/test/heap
xar-1.5.2/test/hardlink
xar-1.5.2/test/validate.c
xar-1.5.2/LICENSE
xar-1.5.2/Makefile.in
xar-1.5.2/src/
xar-1.5.2/src/xar.1
xar-1.5.2/src/xar.c
xar-1.5.2/src/Makefile.inc.in
xar-1.5.2/TODO
xar-1.5.2/configure.ac
xar-1.5.2/xar.spec.in
xar-1.5.2/Mk/
xar-1.5.2/config.sub
xar-1.5.2/install-sh
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ANSI C... none needed
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for _LARGE_FILES value needed for large files... no
checking how to run the C preprocessor... gcc -E
checking for a BSD-compatible install... /usr/bin/install -c
checking for ld... /usr/bin/ld
checking for ar... /usr/bin/ar
checking for ranlib... /usr/bin/ranlib
checking for autoconf... no
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for egrep... grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking ext2fs/ext2_fs.h usability... no
checking ext2fs/ext2_fs.h presence... no
checking for ext2fs/ext2_fs.h... no
checking sys/statfs.h usability... yes
checking sys/statfs.h presence... yes
checking for sys/statfs.h... yes
checking sys/xattr.h usability... yes
checking sys/xattr.h presence... yes
checking for sys/xattr.h... yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking sys/extattr.h usability... no
checking sys/extattr.h presence... no
checking for sys/extattr.h... no
checking libutil.h usability... no
checking libutil.h presence... no
checking for libutil.h... no
checking for lgetxattr... yes
checking for lsetxattr... yes
checking for getxattr... yes
checking for setxattr... yes
checking for getattrlist... no
checking for setattrlist... no
checking for lchmod... no
checking for lchown... yes
checking for chflags... no
checking for statvfs... yes
checking for statfs... yes
checking for strmode... no
checking for struct statfs.f_fstypename... no
checking for struct statvfs.f_fstypename... no
checking for struct stat.st_flags... no
checking for uid_t... yes
checking size of uid_t... 4
checking for gid_t... yes
checking size of gid_t... 4
checking for ino_t... yes
checking size of ino_t... 8
checking for dev_t... yes
checking size of dev_t... 8
checking for acl_get_file in -lacl... no
checking for asprintf... yes
checking for xml2-config... no
configure: error: Cannot configure without xml2-config
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
fatal: destination path 'bomutils' already exists and is not an empty directory.
make: Nothing to be done for 'all'.
install -d /usr/bin
install -d /usr/share/man/man1
install -m 0755 build/bin/mkbom build/bin/dumpbom build/bin/lsbom build/bin/ls4mkbom /usr/bin
install -m 0644 build/man/mkbom.1.gz build/man/dumpbom.1.gz build/man/lsbom.1.gz build/man/ls4mkbom.1.gz /usr/share/man/man1
install -d /usr/bin
install -d /usr/share/man/man1
install -m 0755 build/bin/mkbom build/bin/dumpbom build/bin/lsbom build/bin/ls4mkbom /usr/bin
install -m 0644 build/man/mkbom.1.gz build/man/dumpbom.1.gz build/man/lsbom.1.gz build/man/ls4mkbom.1.gz /usr/share/man/man1
`

**Comment by P1CKLES** [comment]
This issue is regarding the Empire Project install script which is no longer supported. The Empire Mobile app is separate. The issue you're seeing is because Empire utilizes Python2. So if your Kali VM is using Python3 then you won't be able run this setup script. You can try installing Python2.7 and removing Python3.X.

**Comment by lusifer123** [comment]
> This issue is regarding the Empire Project install script which is no longer supported. The Empire Mobile app is separate. The issue you're seeing is because Empire utilizes Python2. So if your Kali VM is using Python3 then you won't be able run this setup script. You can try installing Python2.7 and removing Python3.X.

I am using python 2.7
